version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: alexgroup_catalog_postgres
    restart: always
    environment:
      POSTGRES_DB: alexgroup_catalog
      POSTGRES_USER: alexgroup_user
      POSTGRES_PASSWORD: alexgroup_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: